global:
  image:
    tag: v2.10.5

server:
  replicas: ${server_replica_count}
  service:
    type: ${server_service_type}

  extraArgs:
    - --insecure
    
  # Pod resources configuration
  resources:
    limits:
      cpu: 200m
      memory: 200Mi
    requests:
      cpu: 50m
      memory: 100Mi

dex:
  enabled: false

redis:
  # When redis_ha_enabled is true, Redis HA will be deployed
  enabled: true
  # Resources for Redis pods
  resources:
    limits:
      cpu: 200m
      memory: 150Mi
    requests:
      cpu: 50m
      memory: 75Mi

controller:
  replicas: 1
  # Pod resources configuration
  resources:
    limits:
      cpu: 200m
      memory: 500Mi
    requests:
      cpu: 50m
      memory: 150Mi

repoServer:
  replicas: 1
  # Resources configuration
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 50m
      memory: 128Mi

applicationSet:
  replicaCount: 1
  # Resources configuration
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 50m
      memory: 128Mi

configs:
  params:
    server.disable.auth: "false"
  
  cm:
    admin.enabled: "true"
    statusbadge.enabled: "true"
    resource.compareoptions: |
      ignoreAggregatedRoles: true
    resource.exclusions: |
      - kinds:
        - Secret
    application.instanceLabelKey: argocd.argoproj.io/instance
    timeout.reconciliation: ${reconciliation_timeout}
    
  rbac:
    policy.default: role:readonly
    policy.csv: |
      p, role:org-admin, applications, *, */*, allow
      p, role:org-admin, clusters, get, *, allow
      p, role:org-admin, repositories, get, *, allow
      p, role:org-admin, repositories, create, *, allow
      p, role:org-admin, repositories, update, *, allow
      p, role:org-admin, repositories, delete, *, allow
      g, admin, role:admin
