# This is a basic workflow to help you get started with Actions

name: Terraform Deploy

on:
  push:
    branches: [ "dev", "staging", "prod" ]
  pull_request:
    branches: [ "dev", "staging", "prod" ]
  workflow_dispatch:

jobs:
  
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name }}
    
    permissions:
      contents: 'read'
      pages: 'write'
      id-token: 'write'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to GCP
        id: auth
        uses: google-github-actions/auth@v2
        with:
          project_id: ${{ vars.PROJECT_ID }}
          workload_identity_provider: '${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}'
      
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Format
        run: terraform fmt -recursive

      - name: Terraform Init
        env:
          TF_VAR_project_id: ${{ vars.PROJECT_ID }}
        run: |
          terraform init \
            -backend-config="bucket=${{ vars.TF_STATE_BUCKET }}"

      - name: Terraform Plan
        env:
          TF_VAR_project_id: ${{ vars.PROJECT_ID }}
        run: terraform plan 
    