name: Terraform Deploy Pipeline

on:
  push:
    branches: [ "dev" ]
  pull_request_target:
    branches: [ "prod", "staging" ]
  workflow_dispatch:

jobs:
  plan:
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name }}
    
    permissions:
      contents: 'read'
      id-token: 'write'
      pull-requests: 'write'
      issues: 'write'

    outputs:
      markdown: ${{ steps.plan_markdown.outputs.markdown }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
    
      - name: Authenticate to GCP
        id: auth
        uses: google-github-actions/auth@v2
        with:
          project_id: ${{ secrets.PROJECT_ID }}
          workload_identity_provider: '${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}'
      
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: '1.12.0'

      - name: Terraform Format
        env:
          TF_IN_AUTOMATION: "true"
        run: terraform fmt -check -recursive

      - name: Terraform Init
        env:
          TF_VAR_project_id: ${{ secrets.PROJECT_ID }}
        run: |
          terraform init \
            -backend-config="bucket=${{ secrets.TF_STATE_BUCKET }}"

      - name: Terraform Validate
        env:
          TF_VAR_project_id: ${{ secrets.PROJECT_ID }}
          TF_IN_AUTOMATION: "true"
        run: terraform validate -no-color

      - name: Terraform Plan
        id: plan
        env:
          TF_VAR_project_id: ${{ secrets.PROJECT_ID }}
          TF_IN_AUTOMATION: "true"
        run: |
          # Create deployment plan
          terraform plan -out=terraform-plan.tfplan -no-color

      - name: Output Readable Plan
        id: plan_markdown
        uses: borchero/terraform-plan-comment@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          planfile: terraform-plan.tfplan
          skip-empty: true

      - name: Upload Terraform Plan
        uses: actions/upload-artifact@v4
        with:
          name: terraform-plan
          path: |
            terraform-plan.tfplan
          retention-days: 1

  manual-approval:
    needs: plan
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name }}
    permissions:
      issues: write
      pull-requests: write
    steps:
      - name: Manual Approval
        uses: trstringer/manual-approval@v1
        with:
          secret: ${{ secrets.GITHUB_TOKEN }}
          approvers: ${{ secrets.APPROVERS}}
          minimum-approvals: 1
          issue-title: 'Manual Approval for ${{ github.ref_name }} Deployment'
          issue-body: |
            Please review this deployment to ${{ github.ref_name }}.
            ${{ needs.plan.outputs.markdown }}
          fail-on-denial: true
      - name: Output Readable Plan
        id: plan_markdown
        uses: borchero/terraform-plan-comment@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          planfile: terraform-plan.tfplan
          skip-empty: true


  apply:
    needs: [plan, manual-approval]
    if:
      needs.manual-approval.result == 'success'
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name }}
    
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          project_id: ${{ secrets.PROJECT_ID }}
          workload_identity_provider: '${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}'
      
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: '1.12.0'

      - name: Terraform Init
        env:
          TF_VAR_project_id: ${{ secrets.PROJECT_ID }}
        run: |
          terraform init \
            -backend-config="bucket=${{ secrets.TF_STATE_BUCKET }}"

      - name: Download Terraform Plan
        uses: actions/download-artifact@v4
        with:
          name: terraform-plan

      - name: Terraform Apply
        env:
          TF_VAR_project_id: ${{ secrets.PROJECT_ID }}
          TF_IN_AUTOMATION: "true"
        run: terraform apply -auto-approve terraform-plan.tfplan