name: Sync Branches

on:
  # Trigger when changes are pushed to prod
  push:
    branches: [ "prod" ]

jobs:
  sync-branches:
    name: Sync branches
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.SYNC_PAT }}

      - name: Sync staging from prod
        run: |
          git checkout staging
          git pull
          git merge origin/prod --no-edit
          git push origin staging

      - name: Sync dev from staging
        run: |
          git checkout dev
          git pull
          git merge origin/staging --no-edit
          git push origin dev
